export const mockItems = [
  {
    id: 1,
    name: 'example-repo-name',
    owner: 'deanmlittle',
    link: 'https://google.com',
  },
  {
    id: 2,
    name: 'a-little-bit-longer-repo-name',
    owner: 'reallyReallyReallyLongOwnerName',
    link: 'https://really/long/link/google.com/long/name/kljlkdjfkl/realllllylongname',
  },
  {
    id: 3,
    name: 'vault-2024',
    owner: 'ASCorreia',
    link: 'https://github.com/ASCorreia/vault-2024',
  },
  { id: 4, name: 'example4', owner: 'sallysmith', link: 'https://google.com' },
  {
    id: 5,
    name: 'really-really-extra-long-super-duper-long-repo-name',
    owner: 'jimmyanderson',
    link: 'https://google.com',
  },
  {
    id: 6,
    name: 'example6',
    owner: 'jillanderson',
    link: 'https://google.com/kljlkdjfkl/realllllylongname',
  },
  {
    id: 7,
    name: 'awesome-project',
    owner: 'techguru',
    link: 'https://github.com/techguru/awesome-project',
  },
  {
    id: 8,
    name: 'data-analysis-toolkit',
    owner: 'datascientist42',
    link: 'https://gitlab.com/datascientist42/data-analysis-toolkit',
  },
  {
    id: 9,
    name: 'machine-learning-experiments',
    owner: 'airesearcher',
    link: 'https://github.com/airesearcher/machine-learning-experiments',
  },
  {
    id: 10,
    name: 'web-dev-boilerplate',
    owner: 'frontendwizard',
    link: 'https://github.com/frontendwizard/web-dev-boilerplate',
  },
  {
    id: 11,
    name: 'blockchain-explorer',
    owner: 'cryptoenthusiast',
    link: 'https://bitbucket.org/cryptoenthusiast/blockchain-explorer',
  },
  {
    id: 12,
    name: 'mobile-app-template',
    owner: 'appdeveloper',
    link: 'https://github.com/appdeveloper/mobile-app-template',
  },
  {
    id: 13,
    name: 'game-engine-2d',
    owner: 'gamedev101',
    link: 'https://gitlab.com/gamedev101/game-engine-2d',
  },
  {
    id: 14,
    name: 'devops-tools',
    owner: 'inframaster',
    link: 'https://github.com/inframaster/devops-tools',
  },
  {
    id: 15,
    name: 'cybersecurity-toolkit',
    owner: 'securityninja',
    link: 'https://github.com/securityninja/cybersecurity-toolkit',
  },
  {
    id: 16,
    name: 'iot-home-automation',
    owner: 'smarthomelover',
    link: 'https://bitbucket.org/smarthomelover/iot-home-automation',
  },
  {
    id: 17,
    name: 'data-visualization-library',
    owner: 'chartmaster',
    link: 'https://github.com/chartmaster/data-visualization-library',
  },
  {
    id: 18,
    name: 'serverless-functions-collection',
    owner: 'cloudarchitect',
    link: 'https://gitlab.com/cloudarchitect/serverless-functions-collection',
  },
  {
    id: 19,
    name: 'ar-vr-experiments',
    owner: 'immersivedev',
    link: 'https://github.com/immersivedev/ar-vr-experiments',
  },
  {
    id: 20,
    name: 'quantum-computing-simulator',
    owner: 'quantumcoder',
    link: 'https://github.com/quantumcoder/quantum-computing-simulator',
  },
  {
    id: 21,
    name: 'natural-language-processing-toolkit',
    owner: 'nlpexpert',
    link: 'https://gitlab.com/nlpexpert/natural-language-processing-toolkit',
  },
  {
    id: 22,
    name: 'robotics-control-system',
    owner: 'roboticsengineer',
    link: 'https://github.com/roboticsengineer/robotics-control-system',
  },
  {
    id: 23,
    name: 'cryptocurrency-tracker',
    owner: 'cryptotrader',
    link: 'https://bitbucket.org/cryptotrader/cryptocurrency-tracker',
  },
  {
    id: 24,
    name: 'ethical-hacking-tools',
    owner: 'whitehathacker',
    link: 'https://github.com/whitehathacker/ethical-hacking-tools',
  },
  {
    id: 25,
    name: 'cloud-native-microservices',
    owner: 'distributedarchitect',
    link: 'https://gitlab.com/distributedarchitect/cloud-native-microservices',
  },
  {
    id: 26,
    name: 'bioinformatics-pipeline',
    owner: 'genomicsresearcher',
    link: 'https://github.com/genomicsresearcher/bioinformatics-pipeline',
  },
];
